// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKcR5HyyK1asaufMgN2iVRCh3H0yT0XTY',
    appId: '1:1080002897607:android:69c03cba8f6214b94e00e2',
    messagingSenderId: '1080002897607',
    projectId: 'dornas-cb9aa',
    storageBucket: 'dornas-cb9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJu5qL-rqfFaZnqPBqG8tVscbtQX2r9M',
    appId: '1:1080002897607:ios:3e54853fdaba384f4e00e2',
    messagingSenderId: '1080002897607',
    projectId: 'dornas-cb9aa',
    storageBucket: 'dornas-cb9aa.appspot.com',
    androidClientId: '1080002897607-n7c8pnjch1g6qe2c6jtmrjlh4vrqufvk.apps.googleusercontent.com',
    iosClientId: '1080002897607-s541sgrk1t2a4i7469np7f5g2suc9hbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.dornasApp',
  );

}